language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provide: firebase
  token:
    secure: ekQCHwY/N0GCzE9KVKzjNsUQ29dflhyRXAZ27y+RDF6M3sAHdNaSXK0blNJxeMM9UX6Ee0Znsk9CYudRVGtQBA0g6RMQG4tB54FvVrNQdnIvbgroOxea7zZtpedjVILvTeB8hT3PaKfABJBnIG3+863pobEkbiijb8z838oX/A3RFpVzSe9hBOIdBS7fhfXXcLTWRS4pVUDEZDHfYFXYrZdUboWfrDg7zT/AFYJ+AyVAgcV2bTSoQCp/IqnfZ1Wji/vyvQ7F2E9RgOVBORP96+6jTlL1pOzPiOV5sxpVWNWBSPRDAgHZVG4NfUCGgDLPSVvUZRR/XBpeDyXFu8JGMJqIQAxBieW8Rr6qudup7UZk/tt01e4JFvWS7xWjDh7xll8UocNTCOBGcLAPPrSkwki0SbYuVw/whhXZLqR/89T1i24WulJQUbhZ7bGZtjnhOeOVvrMuqo+WG2Ryv1SV2k9MxIXhrYxqp6Ko1ciTN2/pB/oD0t+Vz8ougiah4EpI5KTMZube1v/wMDSE//7f5aWSIjeR+D6R/d6KsdMjyoqzc2/5/2O+LO1HebFCFYG2ZyMUFBsrNPgMZrZmEFBsYVHpFgk3iyByb3rOs6jGzH2SEvi3JzBJpeJoAkHB4D6Rhzq8o5AsqsD8fP0CPz2vmuVfEZulVF+Iubau43l0Z4k=
